### PR TITLE
ActionPack 5.1 support

### PR DESCRIPTION
**Pull request by mauro-oto**
This PR is a follow-up to https://github.com/fac/hestia/pull/12 and adds support for Rails 5.1.

### CODE REVIEW

**Comment by mauro-oto** [comment]
Travis build: https://travis-ci.org/fac/hestia/builds/292614034

**Comment by mauro-oto** [comment]
@caius any thoughts on merging this or https://github.com/fac/hestia/pull/12?

**Comment by benlangfeld** [comment]
@caius It'd be really great to get this in a release. Do you need any maintenance help?

**Comment by caius** [comment]
@mauro-oto could you merge master into this PR please? Github appears to not update the diff even though master has had #12 merged 🙄

**Comment by etagwerker** [comment]
@caius Thanks for the quick response! I rebased this PR so that it shows the right commits over here. The build is over here: https://travis-ci.org/fac/hestia/builds/309531070 

Please let us know if you need anything else.

**Review by caius — APPROVED** [review]
Nice one!

**Comment by caius** [comment]
No problem, thanks for the rebase.

**Pull request merged**
